### ISSUE TITLE
Removing creation header

### ISSUE THREAD

**Issue by astronati** [sapegin/grunt-webfont#311] opened 2016-01-20 14:05 UTC
We need to have the possibility to remove the metadata tag or at least its content like `Created by FontForge 20150828 at Wed Jan 20 13:46:51 2016`.

**Comment by sapegin** [comment] 2016-01-20 14:29
Duplicate of #171.

**Closed by sapegin** 2016-01-20 14:29 UTC

**Comment by astronati** [comment] 2016-01-20 14:36
It seems the problem is not fixed. How should I remove that string? The documentation doesn't explain that. Could you help me please?

**Comment by sapegin** [comment] 2016-01-20 14:37
It’s not fixed because nobody send a pull request to fix that. I couldn’t find any solution too.

**Comment by astronati** [comment] 2016-01-20 14:45
Can I suggest to leave case opened? I would like to spend some time in the next future to fix it.

**Comment by sapegin** [comment] 2016-01-20 14:46
Just send a pull request if will find a solution.
